In [2]:
import numpy as np
a = np.array([[1, 2], [3, 4]])

In [3]:
import numpy as np
array1 = np.array([[2, 4, 6],
                  [1, 3, 5]])

In [4]:
array1


array([[2, 4, 6],
       [1, 3, 5]])

In [5]:
array1.ndim

2

In [6]:
a.ndim

2

In [7]:
array1.shape

(2, 3)

In [8]:
array1.size

6

In [9]:
array1.dtype

dtype('int32')

In [10]:
array1.itemsize

4

In [11]:
np.mean(a)

2.5

In [12]:
a = np.array([1, 2, 5, 7, 8]) 


In [13]:
a[1:3] = -1 


In [14]:
a

array([ 1, -1, -1,  7,  8])

In [15]:
b = [1, 2, 5, 7, 8]


In [16]:
b[1:3] = -1


TypeError: can only assign an iterable

In [ ]:
a = np.array([1, 2, 5, 7, 8])

In [17]:
a_slice = a[1:5]


In [18]:
a_slice[1] = 1000

In [19]:
a

array([   1,   -1, 1000,    7,    8])

In [20]:
a=[1,2,5,7,8]

In [21]:
b=a[1:5]


In [22]:
b

[2, 5, 7, 8]

In [23]:
b[1]=3


In [24]:
a

[1, 2, 5, 7, 8]

In [25]:
b

[2, 3, 7, 8]

In [26]:
np.arange(4)+5

array([5, 6, 7, 8])

In [27]:
in_arr1 = np.array([[2, -7, 5], [-6, 2, 0]]) 

In [28]:
in_arr2 = np.array([[0, -7, 8], [5, -2, 9]]) 

In [29]:
out_arr = np.multiply(in_arr1, in_arr2)  

In [30]:
out_arr

array([[  0,  49,  40],
       [-30,  -4,   0]])

In [31]:
out_arr = np.dot(in_arr1, in_arr2)  

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [32]:
Marix_a = np.array([[1, 4], [5, 6]])

In [33]:
Marix_b = np.array([[1, 2], [3, 6]])

In [34]:
out_arr = np.dot(Marix_a, Marix_b)  

In [35]:
out_arr

array([[13, 26],
       [23, 46]])

In [38]:
import pandas as pd
dataf = pd.DataFrame([
    ['John Smith','123 Main St',34],
    ['Jane Doe', '456 Maple Ave',28],
    ['Joe Schmo', '789 Broadway',51]
    ],
    columns=['name','address','age'])

In [39]:
dataf

name        address  age
0  John Smith    123 Main St   34
1    Jane Doe  456 Maple Ave   28
2   Joe Schmo   789 Broadway   51

In [40]:
a = np.array([1, 2, 3, 4, 5, 6]) 

In [41]:
a.resize(2,3)

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a = np.array([1, 2, 3, 4, 5, 6]) 

In [44]:
a.resize(3,4)

In [45]:
a

array([[1, 2, 3, 4],
       [5, 6, 0, 0],
       [0, 0, 0, 0]])

In [46]:
df = pd.DataFrame({"Name": ["Tom", "Mike", "Tiffany"],
                   "Language": ["Python", "Python", "R"],
                   "Courses": [5, 4, 7]})


In [47]:
df

Name Language  Courses
0      Tom   Python        5
1     Mike   Python        4
2  Tiffany        R        7

In [48]:
mylist=[1,2,3]

In [49]:
n=np.array(mylist)

In [50]:
type(mylist)

list

In [51]:
type(n)

numpy.ndarray

In [52]:
list=np.array([[1,2,3],[4,5,6]])

In [53]:
list

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
list.shape

(2, 3)

In [55]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
range(10)

range(0, 10)

In [57]:
a=range(10)

In [58]:
a

range(0, 10)

In [59]:
print(a)

range(0, 10)


In [60]:
zero=np.zeros(50)

In [61]:
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.ones(2,)

array([1., 1.])

In [64]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [65]:
mn=np.arange(0,50)

In [66]:
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [67]:
len(mn)

50

In [68]:
mn.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [70]:
o=np.linspace(0,7,10)

In [71]:
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [72]:
len(o)

10

In [73]:
o.resize(5,2)

In [74]:
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [75]:
np.random.randint(1,10,9)

array([7, 5, 5, 2, 6, 3, 4, 1, 8])

In [76]:
mn=np.random.randint(4,15,10)

In [77]:
mn

array([ 6,  9,  9,  9,  4,  5, 10,  5,  5,  4])

In [78]:
mn[1]

9

In [79]:
mn[-1]

4

In [80]:
mn[6:9]

array([10,  5,  5])

In [81]:
mn[3:]

array([ 9,  4,  5, 10,  5,  5,  4])

In [82]:
mn[5:-2]

array([ 5, 10,  5])

In [83]:
mypets=['Lion','cat','birds']

In [84]:
mypets

['Lion', 'cat', 'birds']

In [85]:
import pandas as pd
pd.Series(mypets)

0     Lion
1      cat
2    birds
dtype: object

In [86]:
days=['Mon','Tue','Wed']

In [87]:
course=['Economics','Science','SST']

In [88]:
pd.Series(course)

0    Economics
1      Science
2          SST
dtype: object

In [89]:
pd.Series(course,index=days)

Mon    Economics
Tue      Science
Wed          SST
dtype: object

In [90]:
days=pd.Series(['Mon','Tues','Wed'],index=['day1','day2','day3'])

In [91]:
days

day1     Mon
day2    Tues
day3     Wed
dtype: object

In [92]:
days={'Mon':'day1','Tues':'day2','Wed':'day3'}

In [93]:
days_series=pd.Series(days)

In [94]:
days_series

Mon     day1
Tues    day2
Wed     day3
dtype: object

In [95]:
my_df=pd.DataFrame(np.random.randn(5,5),index='row1 row2 row3 row4 row5'. split(' '),columns='col1 col2 col3 col4 col5'. split(' '))

In [96]:
my_df

col1      col2      col3      col4      col5
row1 -1.536709  2.507218 -1.511996 -0.857626  0.124419
row2  1.629139  1.727358 -1.568660  0.234946 -1.687841
row3  0.892498  1.018345  0.798899  1.428434  0.032317
row4  0.794927 -0.031402 -0.199319  1.077864 -0.399938
row5  0.801483  0.179403 -0.365205 -0.056737 -0.229846

In [97]:
type(my_df)

pandas.core.frame.DataFrame

In [98]:
type(my_df['col1'])

pandas.core.series.Series

In [99]:
my_df['col6']=my_df['col1']*2

In [100]:
my_df

col1      col2      col3      col4      col5      col6
row1 -1.536709  2.507218 -1.511996 -0.857626  0.124419 -3.073418
row2  1.629139  1.727358 -1.568660  0.234946 -1.687841  3.258278
row3  0.892498  1.018345  0.798899  1.428434  0.032317  1.784996
row4  0.794927 -0.031402 -0.199319  1.077864 -0.399938  1.589854
row5  0.801483  0.179403 -0.365205 -0.056737 -0.229846  1.602965

In [101]:
my_df.drop('col4',axis=1)

col1      col2      col3      col5      col6
row1 -1.536709  2.507218 -1.511996  0.124419 -3.073418
row2  1.629139  1.727358 -1.568660 -1.687841  3.258278
row3  0.892498  1.018345  0.798899  0.032317  1.784996
row4  0.794927 -0.031402 -0.199319 -0.399938  1.589854
row5  0.801483  0.179403 -0.365205 -0.229846  1.602965

In [102]:
my_df

col1      col2      col3      col4      col5      col6
row1 -1.536709  2.507218 -1.511996 -0.857626  0.124419 -3.073418
row2  1.629139  1.727358 -1.568660  0.234946 -1.687841  3.258278
row3  0.892498  1.018345  0.798899  1.428434  0.032317  1.784996
row4  0.794927 -0.031402 -0.199319  1.077864 -0.399938  1.589854
row5  0.801483  0.179403 -0.365205 -0.056737 -0.229846  1.602965

In [103]:
my_df.drop('col4',axis=1,inplace=True)

In [104]:
my_df

col1      col2      col3      col5      col6
row1 -1.536709  2.507218 -1.511996  0.124419 -3.073418
row2  1.629139  1.727358 -1.568660 -1.687841  3.258278
row3  0.892498  1.018345  0.798899  0.032317  1.784996
row4  0.794927 -0.031402 -0.199319 -0.399938  1.589854
row5  0.801483  0.179403 -0.365205 -0.229846  1.602965

In [105]:
my_df.drop('row4',axis=0,inplace=True)

In [106]:
my_df

col1      col2      col3      col5      col6
row1 -1.536709  2.507218 -1.511996  0.124419 -3.073418
row2  1.629139  1.727358 -1.568660 -1.687841  3.258278
row3  0.892498  1.018345  0.798899  0.032317  1.784996
row5  0.801483  0.179403 -0.365205 -0.229846  1.602965

In [107]:
my_df.iloc[1]

col1    1.629139
col2    1.727358
col3   -1.568660
col5   -1.687841
col6    3.258278
Name: row2, dtype: float64

In [108]:
data=pd.read_csv('C:\DSML\Datasets\Iris.csv')

In [109]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [110]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [111]:
data.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [112]:
data.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [113]:
import pandas as pd

In [114]:
df=pd.read_csv("c:\DSML\Datasets\Iris.csv")

In [115]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa